apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-jpa-tdd-bdd-h2
spec:
  selector:
    matchLabels:
      app: sb-jpa-tdd-bdd-h2
  replicas: 1
  template:
    metadata:
      labels:
        app: sb-jpa-tdd-bdd-h2
        env: development
    spec:
      containers:
        - name: sb-jpa-tdd-bdd-h2
          image: cloudmahesh/sb-jpa-tdd-bdd-h2:tag1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: sb-jpa-tdd-bdd-h2-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: sb-jpa-tdd-bdd-h2